# Secrets for the application
# Add your secrets here. For example:
# OPENAI_API_KEY = "your-openai-api-key"
# GOOGLE_API_KEY = "your-google-api-key"
# SERPAPI_API_KEY = "your-serpapi-api-key"
# GCS_BUCKET_NAME = "your-gcs-bucket-name"
# FIREBASE_ADMIN_SDK_JSON = """
# {
#   "type": "service_account",
#   "project_id": "your-project-id",
#   ...
# }
# """
